spring.application.name=pgbooking
spring.datasource.url=jdbc:postgresql://localhost:5432/pgbooking_db
spring.datasource.username=postgres
spring.datasource.password=Shambhavi@123
spring.jpa.hibernate.ddl-auto=update